install misc:
    @[ -d ./{{misc}} ] || (echo -e "\033[31;1;merror: \033[0;4mCould not find misc '\033[1m{{misc}}\033[0;4m' to install...\033[0m" && exit 2)
    @ if [ -L ~/.config/{{misc}} ] ; then echo -e "\033[31;1;merror: \033[0;4mEditor '\033[1m{{misc}}\033[0;4m' already softlinked to install...\033[0m" && exit 2 ; fi
    @ if [ -d ~/.config/{{misc}} ] ; then echo -e "\033[31;1;merror: \033[0;4mEditor '\033[1m{{misc}}\033[0;4m' already exists, please remove...\033[0m" && exit 2 ; fi
    ln -s `pwd`/{{misc}} ~/.config/{{misc}}

clean misc:
    -[ -L ~/.config/{{misc}} ] && rm -f ~/.config/{{misc}}

