install editor:
    @[ -d ./{{editor}} ] || (echo -e "\033[31;1;merror: \033[0;4mCould not find editor '\033[1m{{editor}}\033[0;4m' to install...\033[0m" && exit 2)
    @ if [ -L ~/.config/{{editor}} ] ; then echo -e "\033[31;1;merror: \033[0;4mEditor '\033[1m{{editor}}\033[0;4m' already softlinked to install...\033[0m" && exit 2 ; fi
    ln -s `pwd`/{{editor}} ~/.config/{{editor}}

clean editor:
    -[ -L ~/.config/{{editor}} ] && rm -f ~/.config/{{editor}}

