install:
    cp -r ./hypr ~/.config/
    cp -r ./fuzzel  ~/.config/
    cp -r ./waybar  ~/.config/

sync:
    cp -r ~/.config/hypr .
    cp -r ~/.config/fuzzel .
    cp -r ~/.config/waybar .

clean:
    rm -rf ~/.config/hypr
    rm -rf ~/.config/fuzzel
    rm -rf ~/.config/waybar
