install:
    cp -r ./make.conf /etc/portage/make.conf
    cp -r ./package.env /etc/portage/package.env
    cp -r ./package.mask /etc/portage/package.mask
    cp -r ./package.use /etc/portage/package.use
    cp -r ./package.accept_keywords /etc/portage/package.accept_keywords

clean:
    rm -f /etc/portage/make.conf
    rm -f /etc/portage/package.env
    rm -f /etc/portage/package.mask
    rm -f /etc/portage/package.use
    rm -f /etc/portage/package.accept_keywords

